import { Ingredient } from "./Interfaces";

const INGREDIENTS: Ingredient[] = [
  {
    title: "Korv stroganoff",
    ingredients: [
      "300 g falukorv",
      "150 g rökt fläsk, i bit",
      "1 förp grillade paprikor, med spad",
      "3 klyftor vitlök",
      "7 steklökar",
      "0,5 msk rökt paprikapulver",
      "0,5 msk färsk rosmarin (eller torkad)",
      "1 förp krossade tomater",
      "0,5 dl grädde",
    ],
  },
  {
    title: "Korv med bröd",
    ingredients: [
      "8 korvar (eller vegokorvar)",
      "8 korvbröd",
      "Felix tomatketchup osötad",
      "1 rödlök",
      "0,5 dl ättiksprit 12 %",
      "1 dl strösocker",
      "2 dl vatten",
      "1 purjolök",
      "olja",
      "salt",
      "1,5 dl majonnäs",
      "2 msk dijonsenap",
    ],
  },
  {
    title: "Kycklinghamburgare",
    ingredients: [
      "1 förp Korvbrödsbagarn Brooklyn burger buns",
      "4 kycklinglårfiléer",
      "4 dl vetemjöl",
      "2 tsk cayennepeppar",
      "salt",
      "3 dl filmjölk",
      "olja, till fritering",
      "4 dl kål, riven",
      "2 morötter, rivna",
      "1 dl majonnäs",
      "1 dl crème fraîche",
      "2 tsk dijonsenap",
      "1 msk vinäger",
      "salt",
      "peppar",
      "hel saltgurka, skivad",
      "barbequesås",
    ],
  },
  {
    title: "Pasta med tomatsås",
    ingredients: [
      "400 g spaghetti",
      "1 gul lök",
      "4 klyftor vitlök",
      "1 tsk chiliflakes",
      "2-3 msk tomatpuré",
      "400 g konserverade körsbärstomater, i burk",
      "1 dl vatten",
      "4 msk olivolja",
      "1 dl grädde (valfri sort)",
      "salt",
      "peppar",
      "parmesanost, riven",
      "basilika, till garnering",
    ],
  },
  {
    title: "Köttbullar & potatismos",
    ingredients: [
      "500 g köttfärs",
      "4 msk ströbröd",
      "1,5 dl mjölk",
      "1 ägg",
      "0,5 gul lök",
      "salt",
      "peppar",
      "250 g lingon",
      "0,5 dl strösocker",
      "600 g potatis",
      "smör",
      "gräddfil",
      "salt",
      "peppar",
    ],
  },
  {
    title: "Fiskpinnar",
    ingredients: [
      "700 g fiskfilé (torsk, gös eller spätta)",
      "2 ägg, uppvispade",
      "1 dl ströbröd",
      "1 dl vetemjöl",
      "100 g smör",
      "0,5 dl majonnäs",
      "1 äpple, finhackat",
      "1 saltgurka, finhackad",
      "0,5 tsk curry",
      "salt",
      "vitpeppar",
    ],
  },
  {
    title: "Toast Skagen",
    ingredients: [
      "4 skivor surdegsbröd (eller formfranska)",
      "ca 300 g skalade räkor",
      "2 tsk inlagd ingefära, finhackad (gari)",
      "0,5 msk dill",
      "0,5-1 tsk sesamolja",
      "1 dl majonnäs",
      "smör, till stekning",
      "salt",
      "svartpeppar, nymalen",
      "svarta sesamfrön",
      "färsk koriander",
      "limeklyfta",
    ],
  },
  {
    title: "Pannkakor",
    ingredients: [
      "3 dl vetemjöl",
      "3 ägg",
      "6 dl mjölk",
      "2 msk smör, smält",
      "0,5 tsk salt",
      "ev 1 tsk strösocker",
      "smör, till stekning",
    ],
  },
  {
    title: "Wallenbergare",
    ingredients: [
      "500 g kalvfärs, finmalen",
      "1 tsk salt",
      "1 krm svartpeppar, malen",
      "1 krm vitpeppar, malen",
      "3 äggulor",
      "3 dl vispgrädde",
      "1,5 dl ströbröd",
      "50 g smör, att steka i",
      "800 g mandelpotatis",
      "1,5 dl vispgrädde",
      "0,5 dl mjölk",
      "70 g smör",
      "0,5 citron, rivet skal",
      "muskot, riven efter smak",
      "0,5 tsk salt",
      "200 g frysta ärtor (gröna)",
      "vatten",
      "1 msk smör",
      "salt",
      "100 g smör, brynt",
      "rårörda lingon",
    ],
  },
  {
    title: "Kalops",
    ingredients: [
      "2 kg högrev (eller bringa)",
      "2 gula lökar",
      "2 morötter",
      "smör, till stekning",
      "0,5 msk vetemjöl",
      "6 lagerblad",
      "10-15 kryddpepparkorn",
      "4-5 hela nejlikor",
      "2 msk ansjovisspad",
      "salt",
      "peppar",
      "kokt mjölig potatis",
      "inlagda rödbetor",
    ],
  },
  {
    title: "Kroppkakor",
    ingredients: [
      "700 g potatis, helst King Edward",
      "1 dl potatismjöl",
      "3 äggulor",
      "50 g smör, brynt",
      "1 tsk salt",
      "400 g rimmat sidfläsk",
      "1 gul lök",
      "smör, till stekning",
      "2 tsk kryddpeppar, nystött",
      "400 g rimmat sidfläsk, i skivor",
      "rårörda lingon",
      "smör, brynt",
    ],
  },
  {
    title: "Stekt surströmming",
    ingredients: [
      "30 strömmingsflundror (klippta)",
      "3 ägg",
      "4 dl mjölk",
      "0,5 dl dijonsenap",
      "0,5 dl svensk senap",
      "salt",
      "peppar",
      "1 dl rågmjöl",
      "1 dl veteströ",
      "färsk kruspersilja",
      "800 g mjölig potatis",
      "4 dl mjölk",
      "100 g smör",
      "salt",
      "peppar",
      "muskot",
    ],
  },
  {
    title: "Kebab",
    ingredients: [
      "500 g fläskkarré",
      "2-3 klyftor vitlök, finhackade",
      "1 knippe färsk persilja, finhackad",
      "1 citron, rivet skal",
      "1 msk malen spiskummin",
      "1 tsk chilipulver",
      "1 msk salt (efter smak)",
      "0,5 dl neutral olja",
      "1 gul lök, finhackad",
      "2 klyftor vitlök, finhackade",
      "2 msk olja",
      "1 tsk malen spiskummin",
      "1 förp krossade tomater",
      "3 msk chilisås (gärna Heinz)",
      "ca 0,5 tsk chiliflakes",
      "salt (efter smak)",
      "2 chilifrukt, gärna 1 röd och 1 gul",
      "1 rödlök (stor)",
      "2 dl vatten",
      "0,5 dl rödvinsvinäger",
      "salt (efter smak)",
      "2 dl matyoghurt",
      "1 dl crème fraîche",
      "1 limefrukt, saften",
      "salt (efter smak)",
      "1 msk honung",
      "0,5 kruka koriander, finhackad inkl stjälkarna",
      "pitabröd, hembakade (alt. uppvärmda köpta)",
      "några salladsblad, skurna i mindre bitar",
      "2 tomater, tunt skivadde",
      "0,33 gurka, tunt skivad",
      "1 avokado, tunt skivad",
    ],
  },
  {
    title: "Falafel",
    ingredients: [
      "500 g kikärtor, blötlagda",
      "3 gula lökar",
      "2 vitlökar, hela",
      "1 knippe färsk koriander",
      "1 knippe persilja",
      "1 salladslök",
      "4 msk malen spiskummin",
      "1 msk torkad koriander",
      "2 chilifrukter",
      "1 msk salt",
      "1 tsk bikarbonat",
      "2 l olja, till fritering",
      "kvarn eller matberedare",
      "djup kastrull för fritering eller en fritös",
      "hålslev eller sil",
    ],
  },
  {
    title: "Pyttipanna",
    ingredients: [
      "800 g kokt potatis [8-10 st]",
      "2 gula lökar",
      "150 g rökt fläsk",
      "150 g skinka",
      "150 g korv",
      "3-4 msk smör, till stekning",
      "salt",
      "peppar, nymalen",
      "3 dl vispgrädde, till stuvning",
      "1 krm mejram, till stuvning",
      "4 ägg",
      "inlagda rödbetor",
    ],
  },
  {
    title: "Raggmunk",
    ingredients: [
      "800 g fast potatis [8-10 st]",
      "2 dl vetemjöl",
      "1 tsk salt",
      "4 dl standardmjölk",
      "1 ägg",
      "600 g rimmat sidfläsk, skivat",
      "smör, till stekning",
      "5 dl lingon",
      "2 dl strösocker",
    ],
  },
  {
    title: "Falukorv & Gräddstuvade Makaroner",
    ingredients: [
      "800 g falukorv",
      "smör",
      "1 l gammaldags mjölk (eller 3 %)",
      "5 kryddpepparkorn",
      "5 vitpepparkorn",
      "1 lagerblad",
      "1 tsk salt",
      "6 dl gammaldags makaroner",
      "2 dl vispgrädde",
      "1 msk smör",
      "muskot",
      "chilisås",
      "färsk kruspersilja",
    ],
  },
  {
    title: "Sutströmming",
    ingredients: [
      "5-6 surströmming",
      "200 g mandelpotatis",
      "2-3 mjuka tunnbröd (eller skivor hårt tunnbröd)",
      "smör",
      "0,5 rödlök, finhackad",
      "ost (t ex Västerbottenost)",
      "gräslök, fint skuren",
      "dill, fint skuren",
      "gul lök, skivad och smörstekt",
      "äppelmos",
      "crème fraîche",
      "tomat, skivad",
    ],
  },
  {
    title: "Ärtsoppa",
    ingredients: [
      "5 dl gula ärtor",
      "1,5 l vatten, till blötläggning",
      "1,5 l vatten, till kokning",
      "400 g rimmat fläsk",
      "1 gul lök",
      "1 morot",
      "1 tsk torkad timjan",
      "1 tsk mejram",
      "4 hela nejlikor",
      "4 msk skånsk senap",
      "5 pepparkorn",
    ],
  },
];

export { INGREDIENTS };
